server {
    listen 80;

    # Proxy para a API (Backend)
    location ~ ^/ho/(auth|usuarios|prontuarios|agenda|fila|ofertas|dashboard)(/.*)?$ {
        rewrite ^/ho/(.*)$ /$1 break;
        
        proxy_pass         http://projetods_backend:3000;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    # Proxy para o Frontend (Vite)
    location /ho/ {
        proxy_pass         http://projetods_frontend:8080/ho/;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    # Redireciona a raiz para o subdiretório
    location = / {
        return 301 /ho/;
    }
}